version: '3'

services:

  nginx-dev:
    image: ${NGINX_DEV_IMAGE:-nginx:1.13.3-alpine}
    environment:
      VIRTUAL_HOST: ${NGINX_DEV_VIRTUAL_HOST:-dev.lemp.acme.dev, ~^dev\.lemp\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    depends_on:
      - app-dev
    links:
      - app-dev
    volumes:
      - ./nginx/conf.d/default_dev.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    restart: unless-stopped
    network_mode: bridge

  app-dev:
    image: ${APP_DEV_IMAGE:-php:7.0.21-fpm-alpine}
    working_dir: /opt/app
    command: sh run-dev.sh
    env_file:
      - .env-common
      - .env-dev
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./html:/var/www/html
      - ./run-dev.sh:/opt/app/run-dev.sh
    restart: unless-stopped
    network_mode: bridge

  phpmyadmin:
    image: ${PHP_MY_ADMIN_IMAGE:-phpmyadmin/phpmyadmin:4.7.3-1}
    environment:
      VIRTUAL_HOST: ${PHP_MY_ADMIN_VIRTUAL_HOST:-phpmyadmin.lemp.acme.dev, ~^phpmyadmin\.lemp.\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    network_mode: bridge

  db:
    image: ${DB_IMAGE:-mariadb:10.2.7}
    environment:
      MYSQL_ROOT_PASSWORD: teracy # login with root:teracy as root user
      MYSQL_DATABASE: app
      MYSQL_USER: teracy
      MYSQL_PASSWORD: teracy # login with teracy:teracy as user of the "app" database
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    network_mode: bridge

volumes:
  db:
    driver: local
